use new API ethtool_{get|set}_link_ksettings
Avnu/igb_avb pull request #16
Opened 2019-03-01 23:11 UTC by keerockl

From Kernel 4.20,
The ethtool API {get|set}_settings is deprecated.
We move this driver to new API {get|set}_link_ksettings.
This is picked up from kernel commit c19153008ba0f7b86234820e8a87d58806707a15

2019-03-02 00:05 UTC, pinealservo commented
The function CI is failing on is `ethtool_convert_link_mode_to_legacy_u32`, which apparently showed up in `ethtool.h` in kernel 4.7.  I'm not sure if there's anything else it'd fail on.

CI is using kernel 4.4, which is the newest supported kernel version for the Ubuntu 14.04 LTS distro, which is what we're currently building on. The end-of-life date for 14.04 LTS is this April.

It was also the newest kernel for Ubuntu LTS 16.04.0 and .1, but from .2 on it's been 4.8 or greater.

Might be time to change the CI build to a xenial image, which I think this might build fine on.

2019-03-02 00:32 UTC, keerockl commented
Okay thank you for letting me know. yes please review once CI build is updated.

2019-03-04 10:38 UTC, psow requested changes
The function pointers (in ethtool_ops): get_link_ksettings and set_link_ksettings were introduced in the kernel 4.6 - so this code won't compile with any kernel older than that (changes made to kcompat_ethtool.c doesn't matter as this file is not compiled by default). We still need to do it the old way, for older kernels.

2019-04-03 09:11 UTC, psykuter commented
As @psow mentioned we need compability with older kernels, so I open pull request #17 which fix this problem and also correctly works on version 4.20. In my opinion, this request may be closed.

2019-05-24 13:23 UTC, andrew-elder commented
Any comments on this PR? It needs to have conflicts fixed at a minimum!

2019-05-27 07:19 UTC, psow commented
@andrew-elder This issue is already solved in PR #17. So this one can be safely rejected.

2019-05-28 15:00 UTC, andrew-elder commented
@psow - thanks for the update. Closing.

2019-05-28 15:00 UTC, closed without merging